## 線形変換

In [1]:
import torch
from torch import nn

$y = {\bf w}x+{\bf b}$ : torch.nn.Linearを利用

In [2]:
linear = nn.Linear(3, 1)

学習パラメータは${\bf w}$と${\bf b}$（初期値はランダム）

In [33]:
linear.weight # w

Parameter containing:
tensor([[-0.2296,  0.0367, -0.1505]], requires_grad=True)

In [34]:
linear.bias # b

Parameter containing:
tensor([0.3440], requires_grad=True)

## 線形変換モデルクラスの定義

In [47]:
class LinearRegression(nn.Module): # モデルクラスには torch.nn.Module を継承
    """
    線形変換モデルクラス
    """
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(3, 1) # wx+b 初期パラメータはランダム

        # パラメータの設定
        self.linear.weight = nn.Parameter(torch.Tensor([[0.3, -0.4, 0.7]]))
        self.linear.bias = nn.Parameter(torch.Tensor([0.5]))

        
    def forward(self, input_vector):
        """
        順伝搬
        :param input_vector: 入力ベクトル
        :return wx: 出力値
        """
        wx = self.linear(input_vector)
        return wx


In [48]:
# モデルのインスタンス
linear_regression = LinearRegression()

## 順伝搬

In [49]:
input_vector = torch.tensor([[2,3,4]], dtype=torch.float) # 入力ベクトル

In [53]:
output = linear_regression.forward(input_vector) # 順伝搬

In [56]:
output # 計算結果

tensor([[2.7000]], grad_fn=<AddmmBackward>)